# This is a basic workflow to help you get started with Actions

name: CI_iStandy
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  job_1:
      name: config-template
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
