name: build
on:
  push:
  pull_request:
  release:
    types: [published]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_1:
    name: config-template
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
